version: '3'

services:
  nginx_backend:
    image: nginx_backend
    build: 
      context: ./nginx-backend/nginx-backend
    container_name: nginx-backend
    ports:
      - "5136:5136"
    networks:
      - nginx-network

  nginx-frontend:
    container_name: nginx-frontend
    image: nginx_frontend
    build: 
      context: ./nginx-frontend
    ports:
      - "3000:80"
    networks:
      - nginx-network
    depends_on:
      - nginx_backend
    environment:      
      BACKEND_URL: 'http://nginx_backend:5136'

networks:
  nginx-network:
    driver: bridge

    